### ISSUE TITLE
Rank does not accurately represent ties

### ISSUE THREAD

**Issue by Xero314** [benmyerson/pdxpingpong#3]
Currently the rank column is simple a incremented numeric value based on display order.  This should reflect actual rank, including ties being ranked the same.

**Comment by benmyerson** [comment]
I done fucked up.

currently - 1,2,3,4,4,4,4,5,6
should be - 1,2,3,4,4,4,4,8,9

**Comment by benmyerson** [comment]
I un-fucked up.
